/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "API": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "BcvFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "BcvQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ProcessBcvFileFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SecretBcvFileStartPath": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SecretBcvUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SecretTursoUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebApp": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "bcv-bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}