/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "API": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AltEmailsRecipient": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AppClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthClient": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuthServer": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "BcvFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "BcvQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CaptchaSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CaptchaSiteKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HtmlToPdfFunction": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IsrGenFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MailerConfigs": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainApiFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PosthogApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ProcessBcvFile": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ProcessUser": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ReceiptPdfQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ReceiptsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SecretBcvFileStartPath": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SecretBcvUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SecretTursoUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TelegramBotApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TelegramBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TelegramWebhookFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "VerifyAccess": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WebApp": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "WebAssetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "bcv-bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}