/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_VAR_ENV: string
  readonly VITE_IS_DEV: string
  readonly VITE_ISR_PREFIX: string
  readonly VITE_RECAPTCHA_SITE_KEY: string
  readonly VITE_CAPTCHA_ENABLED: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}